# Travis CI script
language: c

os:
- linux

sudo: required

services:
- docker

env:
- BUILD_TYPE=default
#- BUILD_TYPE=android
#- BUILD_TYPE=check-py
#- BUILD_TYPE=cmake

addons:
  apt:
    packages:
    - valgrind
    - git

before_install:
    - wget http://www.us.apache.org/dist/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz -O kafka.tgz
    - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
    - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
    - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
    - sleep 5
    - kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic test --zookeeper localhost:2181
    - echo "hello there" | kafkacat -P -b localhost:9092 -t test

# Hand off to generated script for each BUILD_TYPE
script: ./ci_build.sh
before_deploy: . ./ci_deploy.sh
deploy:
  provider: releases
  api_key:
    # To encrypt your access token run: `travis encrypt -r user/repo`
    secure: <encrypted github access token>
  file_glob: true
  file: ${KAFKAEZQ_DEPLOYMENT}
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME =~ (linux) && $BUILD_TYPE =~ (default)
