################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LIBFASTJSON "libfastjson")
    if (NOT PC_LIBFASTJSON_FOUND)
        pkg_check_modules(PC_LIBFASTJSON "libfastjson")
    endif (NOT PC_LIBFASTJSON_FOUND)
    if (PC_LIBFASTJSON_FOUND)
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LIBFASTJSON_INCLUDE_HINTS ${PC_LIBFASTJSON_INCLUDE_DIRS} ${PC_LIBFASTJSON_INCLUDE_DIRS}/*)
        set(PC_LIBFASTJSON_LIBRARY_HINTS ${PC_LIBFASTJSON_LIBRARY_DIRS} ${PC_LIBFASTJSON_LIBRARY_DIRS}/*)
    endif(PC_LIBFASTJSON_FOUND)
endif (NOT MSVC)

find_path (
    LIBFASTJSON_INCLUDE_DIRS
    NAMES libfastjson/json.h
    HINTS ${PC_LIBFASTJSON_INCLUDE_HINTS}
)

find_library (
    LIBFASTJSON_LIBRARIES
    NAMES libfastjson
    HINTS ${PC_LIBFASTJSON_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LIBFASTJSON
    REQUIRED_VARS LIBFASTJSON_LIBRARIES LIBFASTJSON_INCLUDE_DIRS
)
mark_as_advanced(
    LIBFASTJSON_FOUND
    LIBFASTJSON_LIBRARIES LIBFASTJSON_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
