/*  =========================================================================
    kafkaezq - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of kafkaezq.                                     
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef KAFKAEZQ_LIBRARY_H_INCLUDED
#define KAFKAEZQ_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <sodium.h>
#include <czmq.h>
#include <librdkafka/rdkafka.h>
#include <libfastjson/json.h>

//  KAFKAEZQ version macros for compile-time API detection
#define KAFKAEZQ_VERSION_MAJOR 0
#define KAFKAEZQ_VERSION_MINOR 1
#define KAFKAEZQ_VERSION_PATCH 0

#define KAFKAEZQ_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define KAFKAEZQ_VERSION \
    KAFKAEZQ_MAKE_VERSION(KAFKAEZQ_VERSION_MAJOR, KAFKAEZQ_VERSION_MINOR, KAFKAEZQ_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined KAFKAEZQ_STATIC
#       define KAFKAEZQ_EXPORT
#   elif defined KAFKAEZQ_EXPORTS
#       define KAFKAEZQ_EXPORT __declspec(dllexport)
#   else
#       define KAFKAEZQ_EXPORT __declspec(dllimport)
#   endif
#else
#   define KAFKAEZQ_EXPORT
#endif

//  Project has no stable classes, so we build the draft API
#undef  KAFKAEZQ_BUILD_DRAFT_API
#define KAFKAEZQ_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef KAFKAEZQ_BUILD_DRAFT_API
typedef struct _ksock_t ksock_t;
#define KSOCK_T_DEFINED
#endif // KAFKAEZQ_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef KAFKAEZQ_BUILD_DRAFT_API
#include "ksock.h"
#endif // KAFKAEZQ_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
